language: node_js

dist: noble

node_js:
  - '25'
  - '24'
  - '22'

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: security
      node_js: '22'
      script: npm audit --audit-level=moderate
